### ISSUE TITLE
Publish image with shorter name

### ISSUE THREAD

**Issue by jldec** [projectriff/http-source#8]
Is there a way to direct ko to make the image repo shorter

e.g. `gcr.io/projectriff/http-source`  
instead of the current  
`gcr.io/projectriff/http-source/github.com/projectriff/http-source/cmd`

removing the `-P` in [ko publish](https://github.com/projectriff/http-source/blob/master/.github/workflows/stage.sh#L12) results in something like  
`gcr.io/projectriff/http-source/cmd-89586f746084146907c58338e6fea89b`

from https://github.com/projectriff/http-source/runs/323413981
```
Run .github/workflows/stage.sh
2019/11/27 17:12:56 Using base gcr.io/distroless/static:latest for github.com/projectriff/http-source/cmd
2019/11/27 17:12:56 Building github.com/projectriff/http-source/cmd
2019/11/27 17:13:11 Publishing gcr.io/projectriff/http-source/github.com/projectriff/http-source/cmd:0.1.0-snapshot-20191127171015-8b9d7934ec77a183
2019/11/27 17:13:15 Published gcr.io/projectriff/http-source/github.com/projectriff/http-source/cmd:0.1.0-snapshot-20191127171015-8b9d7934ec77a183@sha256:1f9a771b43b2a1c56580761e2bdd51c5dd56dc58f3d8d7583b75185ce01f83b0
gcr.io/projectriff/http-source/github.com/projectriff/http-source/cmd:0.1.0-snapshot-20191127171015-8b9d7934ec77a183@sha256:1f9a771b43b2a1c56580761e2bdd51c5dd56dc58f3d8d7583b75185ce01f83b0
```

**Comment by jldec** [comment]
Publishing to docker with something similar to the [dev-utils](https://github.com/projectriff/dev-utils/blob/master/.github/workflows/ci.yaml) workflow may make more sense.

**Comment by scothis** [comment]
You could retag the image and give it whatever repo/tag you want.

In general, I like gcr for images that are buried in yaml, and dockerhub for images a user would interact with directly.
